language: haskell
cache:
  directories:
    - $HOME/.cabal/lib
    - $HOME/.ghc

before_script:
  - createuser -s shoeshare_dev
  - createdb shoeshare_test -U shoeshare_dev

before_install:
  - |
    sudo add-apt-repository -y ppa:hvr/ghc
    sudo apt-get update
    sudo apt-get install cabal-install-1.18 ghc-$ghc
    export CABAL=cabal-1.18
    export PATH=/opt/ghc/$ghc/bin:$PATH

install:
  - sudo apt-get -y install hlint
  - $CABAL install yesod-bin
  - $CABAL install $mode --only-dependencies
  - $CABAL configure $mode

script:
  - hlint -c . --ignore="Parse error"
  - yesod test

env:
  - mode="--enable-tests -ferror" ghc=7.6.3
