language: haskell
cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

before_script:
  - createuser -s shoeshare_dev
  - createdb shoeshare_test -U shoeshare_dev

before_install:
  - cabal install $mode --only-dependencies
  - cabal install yesod-bin
  - sudo apt-get -y install hlint

install:
  - cabal configure $mode

script:
  - hlint -c . --ignore="Parse error"
  - yesod test

env:
  - mode="--enable-tests -ferror"
